### ISSUE TITLE
env!() macro is a compile time constant

### ISSUE THREAD

**Issue by museun** [GreenTeaSeb/rufet#1]
https://github.com/GreenTeaSeb/rufet/blob/1a62e7e9f09c6abc6e54b7d12fc7688527f0c34d/src/main.rs#L43

This would keep this from being distributed as a binary, `env!()` would be the `$HOME` env var for whatever machine/user it was compiled under.

The runtime version [`std::env::var`](https://doc.rust-lang.org/std/env/fn.var.html) would be a better candidate.

Ideally, you'd want to store the configuration file in the appropriate `$XDG_CONFIG_PATH` [^1] (or equivalent for other systems)

There are crates that provide this abstraction, such as: [https://docs.rs/directories/4.0.1/directories/]()

[^1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by GreenTeaSeb** [comment]
Thank you for pointing that out, fixed in c28c97690477b9ede57b347a9b78c10da75cf992

**Comment by GreenTeaSeb** [comment]
Thank you for pointing that out! Fixed in c28c97690477b9ede57b347a9b78c10da75cf992
